modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/liopyu/liolib"
license="MIT"
[[mods]]
modId="liolib"
version="1.20.1-0.0.1"
displayName="liolib"
logoFile="liolib.png"
credits="Gecko, Eliot, AzureDoom, Chappie, DerToaster, Tslat"
author="Liopyu"
description='''
Liolib is an animation engine for Minecraft Mods, with support for complex 3D keyframe-based animations, 30+ easings, concurrent animation support, sound and particle keyframes, event keyframes, and more.
'''
[[dependencies.liolib]]
    modId="forge"
    mandatory=true 
    versionRange="[47.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.liolib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
